language: python

python:
  - "2.7"
  - "3.5"

sudo: false

notifications:
  email: false
 
# These dependencies are really only for testing
install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda create -q -n travis-env python=$TRAVIS_PYTHON_VERSION setuptools nose notebook nbformat matplotlib
  - source activate travis-env
  - python setup.py install

# command to run tests
script: 
  - if [[ $TRAVIS_PYTHON_VERSION < 3.0 ]]; then
      nosetests ;
    else 
      nosetests -I test_notebooks.py ;
    fi